# services:
#   nginx:
#     image: nginx:latest
#     container_name: nginx-proxy
#     restart: unless-stopped
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./index.html:/var/www/html/index.html
#     networks:
#       lab-webproxy:
#         ipv4_address: 10.11.0.6

# networks:
#   lab-webproxy:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.11.0.0/16
#           gateway: 10.11.0.1

version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
    networks:
      lab-webproxy:
        ipv4_address: 10.11.0.6

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      lab-webproxy:
        ipv4_address: 10.11.0.5

networks:
  lab-webproxy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/16
          gateway: 10.11.0.1
